name: "Master Builder"
variables:
    version: "1.0"
config:
    commands:
        default:
            name: DemoCommand
            config:
                test_property: changed
    version_scheme:
        config:
            version: "@{{variables.version}}"
            increment: patch
