name: "Master Builder"
variables:
    version: "1.0"
config:
    commands:
        default:
            name: ShellCommand
            config:
                command: tox
                return_output: False
    version_scheme:
        config:
            version: "@{{variables.version}}"
            increment: patch
